WebApplication1/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Interfaces;
using WebApplication1.Models;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    public class FacturaController : Controller
    {
        private readonly IFacturaRepository facturaRepository;

        public FacturaController(IFacturaRepository _facturaRepository)
        {
            facturaRepository = _facturaRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        //Peticiones con ajax
        [HttpGet]
        public JsonResult GetAllFacturas()
        {
            IEnumerable<FacturaVM> list = facturaRepository.GetAll_Facturas().Select(e => new FacturaVM
            {
                NumeroFact = e.NumeroFact,
                Impuesto = e.Impuesto,
                FechaRegistro = e.FechaRegistro,
                Subtotal = e.Subtotal,
                Total = e.Total,
            });

            ResponseVM resp = new ResponseVM(true, "Enviando datos", list);

            return Json(resp);
        }

        [HttpPost]
        public JsonResult Create(FacturaVM facturaDto)
        {
            decimal imp = (decimal)(facturaDto.Impuesto / 100);
            facturaDto.Total =facturaDto.Subtotal + (imp * facturaDto.Subtotal);

            long result = facturaRepository.Create(new Factura 
            { 
                FechaRegistro = facturaDto.FechaRegistro,
                Impuesto = facturaDto.Impuesto,
                Subtotal = facturaDto.Subtotal,
                Total = facturaDto.Total
            });

            ResponseVM response = new ResponseVM(true, null, result);

            return Json(response);
        }

        [HttpPost]
        public JsonResult CreateDetails(DetalleFacturaVM detail)
        {
            int result = facturaRepository.AddDetail(new DetalleFactura
            {
                NumeroFact = detail.NumeroFact,
                Cantidad = detail.Cantidad,
                Precio = detail.Precio,
                IdArticulo = detail.IdArticulo,
                Impuesto = detail.Impuesto,
                Subtotal = detail.Subtotal,
                Total = detail.Total
            });
            
            return Json(result);
        }

    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    @RenderSection("css", required:false)
</head>
<body>
    <aside class="vertical-nav p-3" id="sidebar">

        <!-- Menu Logotipo -->
        <div class="media d-flex align-items-center">
            <img src="~/images/logo.png" alt="logo" width="80" height="80" , class="mr-3 rounded-circle img-thumbnail">
            <div class="media-texto">
                <h4 class="m-0">Kevin Hernández</h4>
                <p class="text-muted mb-0">Ing. Computación</p>
            </div>
        </div>

        <!-- Link to dashboard -->
        <div class="nav flex-column mt-4">
            <a href="/" class="nav-link text-dark"><i class="fa fa-th-large mr-3 text-primary fa-fw"></i>Dashboard</a>
        </div>

        <!-- submenu1 -->
        <p class="text-gray font-weight-bold text-uppercase px-3 small pb-4 mb-0 mt-4">
            Inventario
        </p>
        <div class="nav flex-column">
            <a href="@Url.Action("Index","Articulo")" class="nav-link text-dark"><i class="fas fa-clipboard-list mr-3 text-primary fa-lg"></i>Artículos</a>
        </div>

        <!-- Submenu2 -->
        <p class="text-gray font-weight-bold text-uppercase px-3 small pb-4 mb-0 mt-4">
            Facturacion
        </p>
        <div class="nav flex-column">
            <a href="@Url.Action("Index","Factura")" class="nav-link text-dark"><i class="fas fa-percent mr-3 text-primary fa-lg"></i>Listar Facturas</a>
            <a href="@Url.Action("Create","Factura")" class="nav-link text-dark"><i class="fa fa-th-large mr-3 text-primary fa-fw"></i>Crear Factura</a>
        </div>
    </aside>

    <!-- Contenido de toda la navegacion -->
    <div class="page-content" id="content">
        <div class="main-header navbar navbar-expand mt-2">
            <div class="nav-item">
                <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-0">
                    <i class="fa fa-bars"></i><small class="text-uppercase font-weight-bold"></small>
                </button>
            </div>
        </div>

        <div id="content-main" class="m-3">
            @RenderBody()
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>